source :rubygems

gem "sinatra", :require => "sinatra/base"
gem "sinatra_auth_github"
gem "sinatra-contrib"
gem "sinatra-assetpack"
gem "thin"
gem "haml"
gem "oauth"
gem "json"
gem "coffee-script"
gem "rest-client"
gem "activesupport"
gem "rack"
gem "ruby-trello", :require => "trello"
gem "em-websocket"
gem "backports"
gem "cramp", :git => "git://github.com/bebac/cramp"
gem "capistrano"
